server:
  port: 8080

spring:
  cache:
    type: redis
    redis:
      key-prefix: "hello-test001"
      use-key-prefix: false
      time-to-live: 600s

  redis:
    host: localhost
#    host: 192.168.1.105
    port: 6379
    timeout: 3s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 3
        max-wait: 1ms
    ssl: false