
spring:
  redis:
    host: localhost
    port: 6379
    #    host: 192.168.1.105
    cluster:
      nodes:
      - 192.168.1.105:16379
      - 192.168.1.105:26379
      - 192.168.1.105:36379
    sentinel:
      nodes:
      - 192.168.1.105:16380
      - 192.168.1.105:26380
      - 192.168.1.105:36380
    timeout: 3s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 3
        max-wait: 1ms
    ssl: false


